### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by ShalokShalom** [stefan3372/The-WItcher-3-Mod-manager#8]
I guess this would mean a huge rewrite, while I appreciate a Linux version. 

Thanks!

**Comment by poperigby** [comment]
That would be great!

**Comment by easterwood** [comment]
Since it is written in python it should work I thought. So I tried and got the following error:
```
Traceback (most recent call last):
  File "TheWitcher3ModManager.py", line 7, in <module>
    import Core
  File "/home/alexander/sources/The-WItcher-3-Mod-manager/Core.py", line 3, in <module>
    from Helpers import *
  File "/home/alexander/sources/The-WItcher-3-Mod-manager/Helpers.py", line 6, in <module>
    import ctypes.wintypes
  File "/usr/lib/python3.6/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported
```
Here is import https://github.com/stefan3372/The-WItcher-3-Mod-manager/blob/e9193765016dc71a3f35c31a73ffae724770e1bf/Helpers.py#L6

There are only three lines of code which uses wintypes and it seems this is used to get the base path of the witcher3.exe. This shouldn't be a huge rewrite to make it run on linux.

**Comment by Systemcluster** [comment]
I updated [my fork](https://github.com/Systemcluster/The-Witcher-3-Mod-manager) to run on Linux 👍

**Comment by kristaps777** [comment]
> I updated [my fork](https://github.com/Systemcluster/The-Witcher-3-Mod-manager) to run on Linux 👍

What is the preferred way to mod manage on linux - the original ModManager via Protontricks/Bottles or this fork?
I usually run everything through Bottles, but compilation resulted in a bunch of errors.

`
Error [content0]game\quests\quest_function.ws(9006): Could not find function 'GetCannotUseUndying'
Error [content0]game\quests\quest_function.ws(9015): Could not find function 'SetCannotUseUndyingSkill'
Error [content0]game\gameplay\items\spells\quenentity.ws(89): Could not find function 'IsSuperchargedSign'
Error [content0]game\gameplay\items\spells\yrdenentity.ws(126): Could not find function 'IsSuperchargedSign'
Error [content0]game\player\r4player.ws(11212): Could not find function 'IsSuperchargedSign'
Error [content0]game\player\playerinput.ws(1387): Could not find function 'GetRadialPopupShown'
Error [content0]game\player\playerinput.ws(1394): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1396): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1410): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1412): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1495): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1498): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1501): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1504): Could not find function 'PotionSelectionPopup'
Error [content0]game\player\playerinput.ws(1526): Could not find function 'OilSelectionPopup'
Error [content0]game\player\playerinput.ws(1530): Could not find function 'OilSelectionPopup'
Error [content0]game\player\playerinput.ws(1554): Could not find function 'GetRadialPopupShown'
Error [content0]game\player\playerinput.ws(1588): Could not find function 'GetRadialPopupShown'
Error [content0]game\player\playerinput.ws(1620): Could not find function 'GetRadialPopupShown'
Error [content0]game\player\playerinput.ws(1649): Could not find function 'GetRadialPopupShown'
Error [content0]game\gameplay\actions\baseaction.ws(712): Could not find function 'IsSuperchargedSign'
Error [content0]game\gui\popups\itemselectionpopup.ws(289): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(300): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(311): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(322): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(333): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(345): Could not find function 'EnableRadialInput'
Error [content0]game\gui\popups\itemselectionpopup.ws(394): Could not find function 'EnableRadialInput'
Error [modadditionalperks]game\gameplay\ability\playerabilitymanager.ws(2698): Cannot call private function 'RemoveExtraOilsFromItem' in class 'W3PlayerWitcher' here.
Error [modadditionalperks]game\gameplay\ability\playerabilitymanager.ws(2702): Cannot call private function 'RemoveExtraOilsFromItem' in class 'W3PlayerWitcher' here.

Warning [content0]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
Warning [content0]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.
`
